---
- name: failed one command by condition
  hosts: all
  tasks:
    - name: run a script
      command: echo hello world
      register: command_result
      failed_when: "'world' in command_result.stdout"
      ignore_errors: yes
    - name: see if we get here
      debug:
        msg: hello
